services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.1.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false   # disable security for local dev
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:9.1.4
    container_name: logstash
    depends_on:
      - elasticsearch
    ports:
      - "5000:5000"   # beats input
      - "9600:9600"   # monitoring API
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - logs_data:/logs

  kibana:
    image: docker.elastic.co/kibana/kibana:9.1.4
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  java-app:
    build: ./java-logger
    container_name: java-app
    volumes:
      - logs_data:/logs   # app writes to /logs/app.log
    depends_on:
      - logstash

volumes:
  es_data:
  logs_data: