services:
  opensearch-node1:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - plugins.security.disabled=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=OpensearchAdmin123!
      - plugins.security.audit.type:internal_opensearch
      - plugins.security.audit.enable_rest:true
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
      - ./opensearch-config.yml:/usr/share/opensearch/config/opensearch.yml
      - node1-logs:/usr/share/opensearch/logs
      - opensearch-plugins:/usr/share/opensearch/plugins 
    ports:
      - 9200:9200
      - 9600:9600

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - opensearch-node1

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    environment:
      - OPENSEARCH_HOSTS=http://opensearch-node1:9200
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    depends_on:
      - opensearch-node1

  vector:
    image: timberio/vector:0.41.1-alpine
    container_name: vector
    volumes:
      - ./vector.toml:/etc/vector/vector.toml:ro
      - node1-logs:/app/node1-logs:ro
    depends_on:
      - opensearch-node1
    ports:
      - "8686:8686"
volumes:
  opensearch-data1:
  node1-logs:
  opensearch-plugins:
