[sources.node1_logs]
type = "file"
include = [
  "/app/node1-logs/*.log", 
  "/app/node1-logs/gc.log*"
]

[sinks.opensearch_logs]
type = "elasticsearch"    
inputs = ["node1_logs"]
endpoints = ["http://opensearch-node1:9200"]
mode = "bulk"
healthcheck = true
bulk.index = "vector-logs-%Y.%m.%d"
api_version = "v7"

[api]
enabled = true
address = "http://127.0.0.1:8686"
