input {
  file {
    path => ["/app/i2i_log/i2i-sync-json.log"]
    start_position => "beginning"
    sincedb_path => "/dev/null"  # so it re-reads on container restart
  }
}

filter {
  json {
    source => "message"
  }
}

output {

  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "i2i"
  }
  stdout { codec => rubydebug }
}

# "/app/es_logs/gc.log",
# %{logfile}-%{+YYYY.MM.dd}

#filter {
  # Example: parse log level from java.util.logging format
 # grok {
  #  match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} %{WORD:level}: %{GREEDYDATA:msg}" }
  #}
#}

